version: 2

jobs:
  bionic:
    docker:
      - image: vapor/swift:5.1-bionic
    steps:
      - checkout
      - run: apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4; echo "deb http://repo.yandex.ru/clickhouse/deb/stable/ main/" | tee /etc/apt/sources.list.d/clickhouse.list
      - run: apt-get update; DEBIAN_FRONTEND=noninteractive apt-get install -y clickhouse-server
      - run: service clickhouse-server start
      - run: swift build --enable-test-discovery
      - run: swift test --enable-test-discovery
    environment:
      CLICKHOUSE_SERVER: "127.0.0.1"
      CLICKHOUSE_USER: "default"
      CLICKHOUSE_PASSWORD: ""

workflows:
  version: 2
  tests:
    jobs:
      - bionic